-- Schema H2 para tests (modo PostgreSQL).
-- Replica las entidades JPA usando tipos compatibles con H2 2.x.
-- geometry(Point,4326) no es válido en H2; se usa GEOMETRY como equivalente.

CREATE TABLE IF NOT EXISTS users (
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                         VARCHAR(255) NOT NULL UNIQUE,
    password                      VARCHAR(255) NOT NULL,
    nombre                        VARCHAR(255) NOT NULL,
    apellido                      VARCHAR(255),
    role                          VARCHAR(50)  NOT NULL,
    activo                        BOOLEAN      NOT NULL,
    tipo_motocicleta              VARCHAR(100),
    tipo_sangre                   VARCHAR(10),
    contacto_emergencia_nombre    VARCHAR(255),
    contacto_emergencia_telefono  VARCHAR(50),
    direccion                     VARCHAR(255),
    fecha_creacion                TIMESTAMP
);

CREATE TABLE IF NOT EXISTS puntos_interes (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo            VARCHAR(255) NOT NULL,
    descripcion       VARCHAR(500),
    ubicacion         GEOMETRY     NOT NULL,
    categoria         VARCHAR(50)  NOT NULL,
    estado            VARCHAR(50)  NOT NULL DEFAULT 'ACTIVO',
    fuente_ubicacion  VARCHAR(50)  NOT NULL DEFAULT 'GPS',
    fecha_creacion    TIMESTAMP,
    usuario_id        BIGINT,
    CONSTRAINT fk_punto_usuario FOREIGN KEY (usuario_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS reporte_eventos (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporte_id   BIGINT       NOT NULL,
    usuario_id   BIGINT,
    tipo_evento  VARCHAR(50)  NOT NULL,
    descripcion  VARCHAR(500) NOT NULL,
    timestamp    TIMESTAMP    NOT NULL,
    CONSTRAINT fk_evento_reporte FOREIGN KEY (reporte_id) REFERENCES puntos_interes(id) ON DELETE CASCADE,
    CONSTRAINT fk_evento_usuario FOREIGN KEY (usuario_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS reporte_votos (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  BIGINT      NOT NULL,
    reporte_id  BIGINT      NOT NULL,
    tipo_voto   VARCHAR(50) NOT NULL,
    CONSTRAINT fk_voto_usuario FOREIGN KEY (usuario_id) REFERENCES users(id),
    CONSTRAINT fk_voto_reporte FOREIGN KEY (reporte_id) REFERENCES puntos_interes(id),
    CONSTRAINT uk_usuario_reporte UNIQUE (usuario_id, reporte_id)
);

CREATE TABLE IF NOT EXISTS fotos_reporte (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporte_id    BIGINT       NOT NULL,
    ruta_archivo  VARCHAR(255) NOT NULL,
    fecha_carga   TIMESTAMP,
    CONSTRAINT fk_foto_reporte FOREIGN KEY (reporte_id) REFERENCES puntos_interes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comercios_verificados (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR(255) NOT NULL,
    direccion           VARCHAR(255) NOT NULL,
    telefono            VARCHAR(50),
    categoria           VARCHAR(50)  NOT NULL,
    ubicacion           GEOMETRY     NOT NULL,
    activo              BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_alta          TIMESTAMP,
    fecha_modificacion  TIMESTAMP
);
