-- Schema H2 para tests (modo PostgreSQL).
-- Replica las entidades JPA usando tipos compatibles con H2 2.x.
-- geometry(Point,4326) no es válido en H2; se usa GEOMETRY como equivalente.

CREATE TABLE IF NOT EXISTS users (
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                         VARCHAR(255) NOT NULL UNIQUE,
    password                      VARCHAR(255) NOT NULL,
    nombre                        VARCHAR(255) NOT NULL,
    apellido                      VARCHAR(255),
    role                          VARCHAR(50)  NOT NULL,
    activo                        BOOLEAN      NOT NULL,
    tipo_motocicleta              VARCHAR(100),
    tipo_sangre                   VARCHAR(10),
    contacto_emergencia_nombre    VARCHAR(255),
    contacto_emergencia_telefono  VARCHAR(50),
    direccion                     VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS puntos_interes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo      VARCHAR(255) NOT NULL,
    descripcion VARCHAR(500),
    ubicacion   GEOMETRY     NOT NULL,
    categoria   VARCHAR(50)  NOT NULL,
    usuario_id  BIGINT,
    CONSTRAINT fk_punto_usuario FOREIGN KEY (usuario_id) REFERENCES users(id)
);
